/*
    Nome: FC_MONTA_END
    Descricao : retorna o concatenado do endereço
    Parametros:
        @CEP            CHAR(8),
        @NUM            INT,
    Exemplo de execução:
        SELECT dbo.FC_MONTA_END('21312313',132)
*/
--CRIACAO OU ALTERACAO FUNCTION

CREATE OR ALTER FUNCTION FC_MONTA_END (@CEP CHAR(8), @NUM INT)
RETURNS VARCHAR(255)
BEGIN 
	RETURN(
		SELECT 
			CONCAT(TBAC.NOM_CID,' - ',TBAB.NOM_BAIRRO,', ',TBAR.NOM_RUA,', Nº ',@NUM) AS ENDERECO 
		FROM TB_ADS_LOC TBAL
		INNER JOIN TB_ADS_RUA TBAR	
			ON TBAR.COD_RUA = TBAL.COD_RUA
		INNER JOIN TB_ADS_BAIRRO TBAB 
			ON TBAB.COD_BAIRRO = TBAR.COD_BAIRRO
		INNER JOIN TB_ADS_CID TBAC  
			ON  TBAC.COD_CID = TBAB.COD_CID
		WHERE 
			TBAL.COD_CEP = @CEP
	); 
END;