/*
	Nome: usp_ads_inter_insere_agendamentos
	Descricao : insere agendamento.
	parametros:
		@COD_CPF_USER	CHAR(11), --OBRIGATORIO
		@COD_CPF_VOL	CHAR(11),  --OBRIGATORIO
		@COD_CEP		CHAR(8),  --OBRIGATORIO
		@COD_LOTE		INT,  --OBRIGATORIO
		@DAT_AGDM		DATETIME, --OBRIGATORIO
		@TXT_EXT		VARCHAR(200)
	Exemplo de execução:
		EXEC usp_ads_inter_insere_agendamentos @COD_CPF_USER ='1231231231',@COD_CPF_VOL = '1231231231' ,@COD_CEP = '12345678',@COD_LOTE = 1, @DAT_AGDM = '20210812 13:30',@TXT_EXT = ''
		 
*/
--CRIACAO OU ALTERACAO PROCEDURE
CREATE OR ALTER PROCEDURE usp_ads_inter_insere_agendamentos(
	@COD_CPF_USER	CHAR(11),
	@COD_CPF_VOL	CHAR(11),
	@COD_CEP		CHAR(8),
	@COD_LOTE		INT,
	@DAT_AGDM		DATETIME,
	@TXT_EXT		VARCHAR(200)
)
AS
BEGIN

	DECLARE @QTDVAC INT = 0;
	SET @QTDVAC = ISNULL((SELECT LOTE.QTD_VAC FROM TB_ADS_LOTE LOTE WHERE LOTE.COD_LOTE = @COD_LOTE),0)
	IF @QTDVAC > 0
		BEGIN
			BEGIN TRY  
			INSERT INTO 
				TB_ADS_AGDM(COD_CPF_USER ,
							COD_CPF_VOL ,COD_CEP ,
							COD_LOTE ,DAT_AGDM ,TXT_EXT)
			VALUES (@COD_CPF_USER ,
						@COD_CPF_VOL ,@COD_CEP ,
						@COD_LOTE,@DAT_AGDM ,@TXT_EXT);
			END TRY  
			BEGIN CATCH  
				SELECT   
					ERROR_NUMBER() AS ErrorNumber  ,
					ERROR_MESSAGE() AS ErrorMessage;  
			END CATCH  
		END
	ELSE
		BEGIN
			SELECT 'LOTE ESGOTADO' AS ERRO ;
		END
	
END
GO