CREATE VIEW VW_ULT_AGDM AS 
SELECT TOP(1) 
	AGDM.COD_AGDM, 
	AGDM.COD_CEP, 
	AGDM.COD_CPF_USER, 
	AGDM.COD_CPF_VOL, 
	AGDM.DAT_AGDM, 
	AGDM.TXT_EXT 
FROM TB_ADS_AGDM AGDM
ORDER BY AGDM.DAT_AGDM DESC;

